ADD 1.i Edson Gabriel
univas/css-exercises pull request #1
Opened 2017-03-31 03:02 UTC by EGGabriel

Exercise CSS 1.i Edson Gabriel

2017-04-02 18:25 UTC, edysegura commented on edson-gabriel/1.i/index.html
> +    <p>Lorem ipsum dolor sit amet, consectetur <a>adipiscing</a> elit. Pellentesque non sem a sem suscipit <a>ullamcorper</a> sed non justo.
O elemento `<a>` não é o mais apropriado para essa situação. Utilizei elementos como o `<span>` por exemplo.

2017-04-02 18:26 UTC, edysegura commented on edson-gabriel/1.i/style.css
> +a:hover{
Aqui o ideal é ser mais específico como por example `p .highlight`

2017-04-02 18:27 UTC, edysegura requested changes
Olá @EGGabriel !

Leia os meus comentários e casa tenha dúvida é só me retornar!

Abraços,

2017-04-04 02:48 UTC, edysegura commented on edson-gabriel/1.i/style.css
> +span:hover{
A recomendação é usar o seletor `p:hover span` para não atingir todos os `<span>` do documento

2017-04-04 18:03 UTC, EGGabriel commented
creio eu, que agora tudo está conforme o pedido!

2017-04-05 02:43 UTC, edysegura approved these changes
Good job!

2017-04-05 02:43 UTC, merged